// Static fallback data — mirrors the shape returned by supabaseClient's
// getAlbums()/getRecommendations() (albums.tracks is a nested, sorted array).
// Used automatically when VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are
// missing, so the app always has something to render.
//
// Keep this in sync with the sample INSERTs in schema.sql if you add albums.

export const albums = [
  {
    id: 'local-pacific-1978',
    title: 'Pacific',
    title_jp: 'パシフィック',
    artist: 'Haruomi Hosono, Shigeru Suzuki & Tatsuro Yamashita',
    artist_jp: null,
    year: 1978,
    genre: ['City Pop', 'Exotica', 'Jazz Fusion', 'Instrumental'],
    cover_url: null,
    rating: 4.5,
    synopsis:
      'An instrumental three-way collaboration and the first entry in the CBS/Sony Sound Image series — tropical, genre-hopping, and a direct ancestor of the City Pop sound.',
    funkiness: 55,
    sunset_energy: 90,
    night_drive: 20,
    spotify_url: 'https://open.spotify.com/album/6PnbwR4pgQQZDrLUdw6Kc7',
    tracks: [
      { id: 'local-pacific-1', album_id: 'local-pacific-1978', track_number: 1, title: 'The Last Paradise', duration: '4:03', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-pacific-2', album_id: 'local-pacific-1978', track_number: 2, title: 'Coral Reef', duration: '3:45', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-pacific-3', album_id: 'local-pacific-1978', track_number: 3, title: "Cosmic Surfin'", duration: '5:07', is_highlight: true, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-rideontime-1980',
    title: 'Ride on Time',
    title_jp: 'ライド・オン・タイム',
    artist: 'Tatsuro Yamashita',
    artist_jp: '山下 達郎',
    year: 1980,
    genre: ['City Pop', 'Funk', 'Disco', 'Soul'],
    cover_url: null,
    rating: 4.8,
    synopsis:
      "Yamashita's fifth studio album, driven by the Maxell-commercial hit title track and a sharp, funk-forward studio band.",
    funkiness: 90,
    sunset_energy: 55,
    night_drive: 70,
    spotify_url: 'https://open.spotify.com/artist/2iojnvSXbLKLA4XoSjMPQO',
    tracks: [
      { id: 'local-rot-1', album_id: 'local-rideontime-1980', track_number: 1, title: 'Ride on Time', duration: '4:25', is_highlight: true, preview_url: null, spotify_track_id: null },
      { id: 'local-rot-2', album_id: 'local-rideontime-1980', track_number: 2, title: 'The Door into Summer', duration: '4:41', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-rot-3', album_id: 'local-rideontime-1980', track_number: 3, title: 'My Sugar Babe', duration: '4:11', is_highlight: false, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-pocketpark-1980',
    title: 'Pocket Park',
    title_jp: 'ポケットパーク',
    artist: 'Miki Matsubara',
    artist_jp: '松原 みき',
    year: 1980,
    genre: ['City Pop', 'Disco', 'AOR'],
    cover_url: null,
    rating: 4.8,
    synopsis:
      "Matsubara's debut album, recorded at 19, anchored by \"Mayonaka no Door / Stay with Me\" — a 1979 single that found a whole new global audience in 2020.",
    funkiness: 70,
    sunset_energy: 50,
    night_drive: 75,
    spotify_url: 'https://open.spotify.com/album/1VS8e1raK66dzG2RijR3Ee',
    tracks: [
      { id: 'local-pp-1', album_id: 'local-pocketpark-1980', track_number: 1, title: 'Mayonaka no Door / Stay With Me', duration: '5:13', is_highlight: true, preview_url: null, spotify_track_id: null },
      { id: 'local-pp-2', album_id: 'local-pocketpark-1980', track_number: 2, title: "It's So Creamy", duration: '3:38', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-pp-3', album_id: 'local-pocketpark-1980', track_number: 3, title: "Cryin'", duration: '3:58', is_highlight: false, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-seabreeze-1981',
    title: 'Sea Breeze',
    title_jp: 'シー・ブリーズ',
    artist: 'Toshiki Kadomatsu',
    artist_jp: '角松 敏生',
    year: 1981,
    genre: ['City Pop', 'Funk', 'Soul'],
    cover_url: null,
    rating: 4.6,
    synopsis:
      "Kadomatsu's debut, cut while he was still a university student — a late-night-beach record built for driving with the windows down.",
    funkiness: 85,
    sunset_energy: 75,
    night_drive: 65,
    spotify_url: 'https://open.spotify.com/artist/1H9waHKgIuUL0Ya1vLcgJ4',
    tracks: [
      { id: 'local-sb-1', album_id: 'local-seabreeze-1981', track_number: 1, title: 'Dancing Shower', duration: '4:41', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-sb-2', album_id: 'local-seabreeze-1981', track_number: 2, title: 'Elena', duration: '5:21', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-sb-3', album_id: 'local-seabreeze-1981', track_number: 3, title: 'Yokohama Twilight Time', duration: '5:14', is_highlight: true, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-foryou-1982',
    title: 'For You',
    title_jp: 'フォー・ユー',
    artist: 'Tatsuro Yamashita',
    artist_jp: '山下 達郎',
    year: 1982,
    genre: ['City Pop', 'AOR', 'Funk'],
    cover_url: null,
    rating: 4.9,
    synopsis:
      "Yamashita's Oricon #1 follow-up to Ride on Time — polished, summery, and packed with future standards like \"Sparkle.\"",
    funkiness: 80,
    sunset_energy: 85,
    night_drive: 45,
    spotify_url: 'https://open.spotify.com/artist/2iojnvSXbLKLA4XoSjMPQO',
    tracks: [
      { id: 'local-fy-1', album_id: 'local-foryou-1982', track_number: 1, title: 'Sparkle', duration: '4:16', is_highlight: true, preview_url: null, spotify_track_id: null },
      { id: 'local-fy-2', album_id: 'local-foryou-1982', track_number: 2, title: 'Music Book', duration: '5:10', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-fy-3', album_id: 'local-foryou-1982', track_number: 3, title: 'Loveland, Island', duration: '4:30', is_highlight: false, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-timely-1983',
    title: 'Timely!!',
    title_jp: 'タイムリー',
    artist: 'Anri',
    artist_jp: '杏里',
    year: 1983,
    genre: ['City Pop', 'Funk', 'Boogie'],
    cover_url: null,
    rating: 4.7,
    synopsis:
      "Anri's first Oricon #1 album, arranged and produced top-to-bottom by Toshiki Kadomatsu. Contains the \"Cat's Eye\" re-recording.",
    funkiness: 82,
    sunset_energy: 60,
    night_drive: 50,
    spotify_url: 'https://open.spotify.com/artist/1nna2wJgUpQ4l0oDPfhrIA',
    tracks: [
      { id: 'local-tl-1', album_id: 'local-timely-1983', track_number: 1, title: "Cat's Eye (New Take)", duration: '3:09', is_highlight: true, preview_url: null, spotify_track_id: null },
      { id: 'local-tl-2', album_id: 'local-timely-1983', track_number: 2, title: 'Windy Summer', duration: '4:06', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-tl-3', album_id: 'local-timely-1983', track_number: 3, title: 'Stay By Me', duration: '3:37', is_highlight: true, preview_url: null, spotify_track_id: null },
    ],
  },
  {
    id: 'local-variety-1984',
    title: 'Variety',
    title_jp: 'ヴァラエティ',
    artist: 'Mariya Takeuchi',
    artist_jp: '竹内 まりや',
    year: 1984,
    genre: ['City Pop', 'AOR', 'Boogie'],
    cover_url: null,
    rating: 4.9,
    synopsis:
      'Produced by Tatsuro Yamashita, this glossy 1984 record pairs boogie-funk grooves with breezy AOR balladry. Home to the genre-defining "Plastic Love."',
    funkiness: 88,
    sunset_energy: 65,
    night_drive: 55,
    spotify_url: 'https://open.spotify.com/album/6ztqp2W1kFhw4vgKM0Oihx',
    tracks: [
      { id: 'local-var-1', album_id: 'local-variety-1984', track_number: 1, title: 'Plastic Love', duration: '4:55', is_highlight: true, preview_url: null, spotify_track_id: null },
      { id: 'local-var-2', album_id: 'local-variety-1984', track_number: 2, title: 'Sweetest Music', duration: '4:15', is_highlight: false, preview_url: null, spotify_track_id: null },
      { id: 'local-var-3', album_id: 'local-variety-1984', track_number: 3, title: 'Song for U.S.A.', duration: '4:31', is_highlight: false, preview_url: null, spotify_track_id: null },
    ],
  },
]

export const recommendations = [
  {
    id: 'local-rec-1',
    album_title: 'Down Town',
    artist: 'Sugar Babe',
    user_name: 'yuki_nightdrive',
    note: 'The one that started it all for me — 1975 and it still sounds ahead of its time.',
    vibe: 'Rainy Tokyo Night',
    rating: 4.8,
    created_at: '2026-06-01T12:00:00.000Z',
  },
  {
    id: 'local-rec-2',
    album_title: 'Bi・Ki・Ni',
    artist: 'Anri',
    user_name: 'cassette_dreamer',
    note: 'Slept on compared to Timely!! but the second side is non-stop.',
    vibe: 'Sunset Drive',
    rating: 4.3,
    created_at: '2026-06-03T12:00:00.000Z',
  },
  {
    id: 'local-rec-3',
    album_title: 'Magical',
    artist: 'Junko Ohashi',
    user_name: 'shibuya_scanner',
    note: '"Telephone Number" alone is worth the whole album.',
    vibe: 'Late-Night Cruise',
    rating: 4.6,
    created_at: '2026-06-05T12:00:00.000Z',
  },
]
